---
services:
  ntfy:
    container_name: ntfy
    image: docker.io/binwiederhier/ntfy
    env_file:
      - .env
    volumes:
      - cache:/var/cache/ntfy
      - ./config:/etc/ntfy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.mckay.one`)"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.routers.ntfy.tls.certresolver=cf"
    networks:
      - proxy
    restart: unless-stopped
    command:
      - serve
networks:
  proxy:
    external: true

volumes:
  cache:
