---
services:
  traefik:
    container_name: traefik
    image: "docker.io/traefik:latest"
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "3001:8080"
    volumes:
      - "./config:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/ssl:/ssl-certs"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.traefik.service=api@internal"
#      - "traefik.http.services.service.loadbalancer.server.port=8080"
#      - "traefik.http.routers.traefik-dash.entrypoints=websecure"
#      - "traefik.http.routers.traefik-dash.rule=Host(`traefik-dash.mckay.one`)" # && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
#      - "traefik.http.routers.traefik-dash.tls=true"
#      - "traefik.http.routers.traefik-dash.tls.certresolver=cf"
#      - "traefik.http.routers.traefik-dash.middlewares=auth@docker"
#      - "traefik.http.middlewares.auth.basicauth.users=tekjoey:$$apr1$$6OVGVvax$$DE8Bimg1hibzDO38acN0U0"
#      - "traefik.http.middlewares.auth.basicauth.removeheader=true"
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"

networks:
  proxy:
    external: true
