services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v0.9.12
    env_file: .env
#    ports:
#      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.rule=Host(`home.mckay.one`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=cf"
#      - "traefik.http.routers.homepage.middlewares=authentik@file"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
