---
services:
  app:
    image: docker.io/louislam/uptime-kuma:1.23.16
    ports:
      - 3002:3001
    volumes:
      - data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.rule=Host(`up.mckay.one`)"
      - "traefik.http.routers.uptime.tls=true"
      - "traefik.http.routers.uptime.tls.certresolver=cf"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  data:
    driver_opts:
      type: nfs
      o: addr=truenas.mckay.one,nfsvers=4,rw
      device: ":/mnt/McPool/docker/uptime-kuma/data"
