services:
  app:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: karakeep-app
    restart: unless-stopped
    volumes:
      - data:/data
    # ports:
    #   - 3000:3000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep.entrypoints=websecure"
      - "traefik.http.routers.karakeep.rule=Host(`bookmarks.mckay.one`)"
      - "traefik.http.routers.karakeep.tls=true"
      - "traefik.http.routers.karakeep.tls.certresolver=cf"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - karakeep
  chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:release
    container_name: karakeep-chrome
    restart: unless-stopped
    init: true
    command:
      - --disable-gpu
      - --disable-dev-shm-usage
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900
    networks:
      - karakeep
  meilisearch:
    image: getmeili/meilisearch:v1.41.0
    container_name: karakeep-meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
    networks:
      - karakeep

volumes:
  data:
    driver_opts:
      type: nfs
      o: addr=truenas.mckay.one,nfsvers=4,rw
      device: ":/mnt/McPool/docker/karakeep/data"
  meilisearch:

networks:
  karakeep:
  proxy:
    external: true
