---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets/

- logo:

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      hour12: false
      timeZone: America/New_York
      weekday: long
      day: 2-digit
      month: short
      hour: 2-digit
      minute: 2-digit

- resources:
    #cpu: true
    #memory: true
    # disk: /

- openmeteo:
    label: Columbia # optional
    latitude: 34.000710
    longitude: -81.034813
    timezone: America/New_York # optional
    units: imperial # or metric
    cache: 30 # Time in minutes to cache API responses, to stay within limits



